apiVersion: v1
kind: Secret
metadata:
  name: jesussanchez-api-secret
  namespace: jesussanchez-api-ns
  labels:
    app: jesussanchez-api

type: Opaque
data:
  username: c2E=
  password: cGFzc3dvcmQ=