apiVersion: v1
kind: ConfigMap
metadata:
  name: jesussanchez-api-config
  namespace: jesussanchez-api-ns
  labels:
    app: jesussanchez-api

data:
  APP_ENV: "produccion"
  APP_PORT: "8085"
  APP_VERSION: "1.0.0"